# Generated by Django 4.2.19 on 2025-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=100)),
                ('Company_address', models.TextField()),
                ('Company_rating', models.IntegerField()),
            ],
        ),
    ]
