# Generated by Django 4.2.19 on 2025-03-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_id_company_company_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
