# Generated by Django 4.2.19 on 2025-03-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('join_date', models.DateField(verbose_name=models.DateField(auto_now=True, auto_now_add=True, verbose_name='Join Date'))),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
