# Generated by Django 4.2.19 on 2025-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(verbose_name=models.DateField(auto_now_add=True, verbose_name='Join Date')),
        ),
    ]
