# Generated by Django 4.2.19 on 2025-02-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=14)),
                ('address', models.TextField()),
                ('age', models.IntegerField(max_length=2)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
